### ISSUE TITLE
Dockercloud-agent registration failed

### ISSUE THREAD

**Issue by rafagsiqueira** [docker/dockercloud-agent#1]
Hello,
I have two identical VPS servers that I would like to use as byo nodes in Docker Cloud. While one of them registered successfully in Docker cloud, the other one keeps trying to register and failing. /var/log/agent.log shows Registration failed, 402. Trying again in 8s, 16s, 32s...

**Comment by amegianeg** [comment]
Hi there! 402 means payment required, can you check your billing info?

**Comment by rafagsiqueira** [comment]
I am using the trial license. Did not know it was limited to one node.
