### ISSUE TITLE
Agent reports "token is empty" although it clearly isn't

### ISSUE THREAD

**Issue by crockpotveggies** [docker/dockercloud-agent#19]
Trying to work around this issue (https://github.com/docker/dockercloud-agent/issues/18), looks like I exposed another one...

When I look at my `/etc/dockercloud/agent/dockercloud-agent.conf` it is clearly filled in with info, and this is after I set the token using `dockercloud-agent set Token=xxxxx`.

```
{"CertCommonName":"","DockerHost":"tcp://0.0.0.0:2375","Host":"https://cloud.docker.com/","Token":"xxxxx","UUID":"","DockerOpts":""}
```

However, each time I run `sudo service dockercloud-agent start` it erases the config back to this, causing the error in the following log and preventing startup:

```
{"CertCommonName":"","DockerHost":"tcp://0.0.0.0:2375","Host":"https://cloud.docker.com/","Token":"","UUID":"","DockerOpts":""}
```

Logfile:

```
2016/06/22 17:18:12 Checking if config file exists
2016/06/22 17:18:12 Loading Configuration file
2016/06/22 17:18:12 Registering in Docker Cloud via POST: https://cloud.docker.com/api/agent/v1/node/
2016/06/22 17:18:12 The token is empty. Please run 'dockercloud-agent set Token=xxx' first!
2016/06/22 17:18:12 Running dockercloud-agent: version 1.1.0
2016/06/22 17:18:12 Create pid file(/var/run/dockercloud-agent.pid): 1781
2016/06/22 17:18:12 Checking if config file exists
2016/06/22 17:18:12 Loading Configuration file
2016/06/22 17:18:12 Registering in Docker Cloud via POST: https://cloud.docker.com/api/agent/v1/node/
2016/06/22 17:18:12 The token is empty. Please run 'dockercloud-agent set Token=xxx' first!
```

**Comment by crockpotveggies** [comment]
Realized this is being reset if `UUID` is empty. Is that the intended functionality? It seems to break setup?

**Comment by tifayuki** [comment]
@crockpotveggies 

When the agent receives a 401 during the registration, it removes the token from the config file. 
If you provide a new token, the agent will try to register to dockercloud with the new token and the existing UUID.

However, if the UUID and the token doesn't match somehow, dockercloud will return a 401, and the agent will clear the token and exit.(I think this is what happened to you)

Thus, if you want to register the node with a new token, you'd better remove the UUID as well.

**Comment by crockpotveggies** [comment]
Okay going to close this, understand it a little better now ;)

**Comment by jjmonsalveg** [comment]
Hello, How can I get the token and uuid?
