### ISSUE TITLE
name resolving between stacks not working

### ISSUE THREAD

**Issue by tpaz** [docker/dockercloud-agent#2]
am I really the first one or it's not the right place?

tried latest docker-cloud by installing the dockercloud-agent according to documentation.
in Tutum it worked fine when following the guidelines to connect between a service in one stack to one in another (via service_name.stack_name). 
With docker cloud we keep getting 127.0.53.53 as a hint that the DNS agent actually goes to some public DNS instead of resolving the names internally. ping from withing the container to other containers/service names within the stack works fine.

docker version 1.9.1-cs2, build 4ade326 (the dockercloud-agent installed it I believe)

**Comment by tpaz** [comment]
update: we work-around this issue by concatenating the search name from /etc/resolv.conf to the upstream host name, i.e. "service_name.stack_name.$(head -1 /etc/resolv.conf | cut -d ' ' -f 2)"

that's funny that this DNS service is totally public and thus could expose internal ips topology to any outside query...

**Comment by fermayo** [comment]
I see you have created the topic on the Docker Forums - thanks, that's the right place to discuss this. I'll reply there.
