### ISSUE TITLE
How to apply custom DOCKER_OPTS?

### ISSUE THREAD

**Issue by levino** [docker/dockercloud-agent#33]
How can I configure the docker daemon run by dockercloud agent?

**Comment by levino** [comment]
There is a "DockerOptions" field in
```sudo nano /etc/dockercloud/agent/dockercloud-agent.conf```

What is the syntax to add values?

**Comment by tifayuki** [comment]
@Levino 
just put the the same string you run with docker daemon, something like: `-D --log-driver json-file`

**Comment by levino** [comment]
Thanks
