### ISSUE TITLE
How do I change the Docker image installation directory?

### ISSUE THREAD

**Issue by hyacinthus** [docker/dockercloud-agent#34]
Edit my /etc/default/docker file with the -g option does not work any more.

**Comment by tifayuki** [comment]
In Docker Cloud, docker daemon is managed by the agent.
You can go to `/etc/dockercloud/agent/dockercloud-agent.conf` and modify `DockerOpts` there.

**Comment by hyacinthus** [comment]
Thank you, I'll try it later.

**Comment by hyacinthus** [comment]
It works.
