### ISSUE TITLE
Raspberry Pi support

### ISSUE THREAD

**Issue by VadzimBelski-ScienceSoft** [docker/dockercloud-agent#41]
Hi,
When do you plan support RPI ?

```
$ curl -Ls https://get.cloud.docker.com/ | sudo -H sh -s xxxx
ERROR: Unsupported architecture: armv7l
Only x86_64 architectures are supported at this time
Learn more: https://docs.docker.com/docker-cloud/tutorials/byoh/
```

**Comment by alyyousuf7** [comment]
+1
RaspberryPi 0 W - armv6l

**Comment by tifayuki** [comment]
@VadzimBelski-ScienceSoft @alyyousuf7 
We are not going to support new platforms any more in the current "classic" docker cloud, only fixing bugs. You can try our "swarm" mode instead, which has a seamless integration with docker for mac/windows. And the UI is coming in a couple of weeks.

**Comment by fcrisciani** [comment]
@tifayuki is there are guide to how to BYON on docker cloud for the raspberry pi?
