### ISSUE TITLE
Docker Cloud does not save BUILD LOCATION in Configure Automated Builds

### ISSUE THREAD

**Issue by eduDorus** [docker/dockercloud-agent#43]
Hello Docker Team,

Docker Cloud does not save the option BUILD LOCATION in "Configure Automated Builds". When I set the option to "Build on my own Nodes" it does not persist. In the next CI Cycle, the container is getting build on docker servers in San Francisco. Could you please fix this.

I'm available for any further information 😃 

Kindly regards, edudorus

**Comment by tifayuki** [comment]
@eduDorus 
This issue is unrelated to this repo. You can submit a support ticket on the webpage, or open a topic on the docker forum. I am going to close it.

Also @bernardopericacho @amegianeg, do you have any idea about this issue?
