### ISSUE TITLE
AWS server unreachable

### ISSUE THREAD

**Issue by gsvijayraajaa** [docker/dockercloud-agent#46]
HI,

I have created a EC2 node from docker cloud. I tried to modify the default security group to allow the below ports:

```
UDP 6783 0.0.0.0
TCP 6783 0.0.0.0
TCP 2375 0.0.0.0
TCP 22 0.0.0.0
TCP 80 0.0.0.0
TCP 443 0.0.0.0
```

Initially there were no issues but after sometimes the server became unreachable. I had to open all the ports to make docker cloud work again. In this context, kindly let me know what all port is to be opened for docker cloud to work with AWS?

Regards,
Vijay Raajaa G S

**Comment by bernardopericacho** [comment]
Hi, can you disable port allowing port 2375 in your security group and restart the node? That way we will create a reverse tunnel to access it

**Comment by gsvijayraajaa** [comment]
By disable port, did you mean to remove 2375 port from the security group
by? Also, Will docker agent restart be sufficient instead of a node
restart?

**Comment by tifayuki** [comment]
@gsvijayraajaa 
Yes, remove the port 2375 from security group. And restarting the agent also works, you can do this by `service dockercloud-agent restart`

**Comment by gsvijayraajaa** [comment]
I did remove 2375 from security group and restarted docker cloud agent. It was all fine for some 8-10hrs. Now the server shows up as unreachable from docker cloud. 

Snapshot of current security group setup :

```
Custom UDP Rule | UDP | 6783 | 0.0.0.0/0 |  
Custom UDP Rule | UDP | 6783 | ::/0 |  
HTTP | TCP | 80 | 0.0.0.0/0 |  
HTTP | TCP | 80 | ::/0 |  
SSH | TCP | 22 | 0.0.0.0/0 |  
SSH | TCP | 22 | ::/0 |  
Custom TCP Rule | TCP | 6783 | 0.0.0.0/0 |  
Custom TCP Rule | TCP | 6783 | ::/0 |  
HTTPS | TCP | 443 | 0.0.0.0/0 |  
HTTPS | TCP | 443 | ::/0
```

Kindly confirm if something is to be modified here.

Thanks,
Vijay Raajaa GS

**Comment by gsvijayraajaa** [comment]
It resumed the connectivity after sometime. Not sure if the port had anything to do with it. The security group update seems to have fixed the issue.

Thanks,
Vijay Raajaa  G S
